In [1]:
import torch
import torchvision

In [2]:
x = torch.empty(1)
print(x, type(x), x.shape)

x = torch.empty((3,3))
print(x, x.shape, x.ndim)

#y = torch.empty(3,3)
#print(y)

tensor([-5.8239e-11]) <class 'torch.Tensor'> torch.Size([1])
tensor([[-5.9118e-11,  1.1519e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]) torch.Size([3, 3]) 2


In [3]:
r = torch.rand(3,3)

print(r, r.shape, type(r))

tensor([[0.8258, 0.7900, 0.3931],
        [0.4598, 0.8223, 0.5266],
        [0.0187, 0.8388, 0.3663]]) torch.Size([3, 3]) <class 'torch.Tensor'>


In [4]:
r0 = torch.zeros(3,3)
r1 = torch.ones(3,3)

print(r0, r1)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [5]:
A = [2.5, 0.1]
x = torch.tensor(A)
print(x)

tensor([2.5000, 0.1000])


In [6]:
x = torch.rand(2,2)
y = torch.rand(2,2)
print("Tensor x: ",x)
print("Tensor y: ",y)
print("Tensor x*y: ", x*y)
print("Tensor x + y: ", x+y)
print("Tensor x/y: ", x/y)
print("Tensor x - y: ", x-y)


Tensor x:  tensor([[0.8000, 0.8245],
        [0.9820, 0.8873]])
Tensor y:  tensor([[0.0816, 0.4816],
        [0.6468, 0.6606]])
Tensor x*y:  tensor([[0.0653, 0.3971],
        [0.6351, 0.5862]])
Tensor x + y:  tensor([[0.8816, 1.3062],
        [1.6288, 1.5480]])
Tensor x/y:  tensor([[9.8033, 1.7119],
        [1.5183, 1.3432]])
Tensor x - y:  tensor([[0.7184, 0.3429],
        [0.3352, 0.2267]])


In [7]:
print("Tensor x*y: ", torch.mul(x, y))
print("Tensor x + y: ", torch.add(x, y))
print("Tensor x - y: ", torch.sub(x, y))

Tensor x*y:  tensor([[0.0653, 0.3971],
        [0.6351, 0.5862]])
Tensor x + y:  tensor([[0.8816, 1.3062],
        [1.6288, 1.5480]])
Tensor x - y:  tensor([[0.7184, 0.3429],
        [0.3352, 0.2267]])


In [8]:
x = torch.rand(4,4)
print(x)

y = x.view(16)
print(y)

y1 = x.view(2,8)
print(y1)

y2  = x.view(-1,8)
print(y2)

tensor([[0.5221, 0.5300, 0.0853, 0.3741],
        [0.5290, 0.6573, 0.1830, 0.4634],
        [0.5050, 0.5244, 0.4195, 0.0489],
        [0.3838, 0.9150, 0.1943, 0.5426]])
tensor([0.5221, 0.5300, 0.0853, 0.3741, 0.5290, 0.6573, 0.1830, 0.4634, 0.5050,
        0.5244, 0.4195, 0.0489, 0.3838, 0.9150, 0.1943, 0.5426])
tensor([[0.5221, 0.5300, 0.0853, 0.3741, 0.5290, 0.6573, 0.1830, 0.4634],
        [0.5050, 0.5244, 0.4195, 0.0489, 0.3838, 0.9150, 0.1943, 0.5426]])
tensor([[0.5221, 0.5300, 0.0853, 0.3741, 0.5290, 0.6573, 0.1830, 0.4634],
        [0.5050, 0.5244, 0.4195, 0.0489, 0.3838, 0.9150, 0.1943, 0.5426]])


### Tensor to Numpy Array

In [9]:
import numpy as np

a = torch.ones((5))
print(a)

a_np = np.array([0.5,0.4,2])
print(a_np)

b_tensor = torch.tensor(a_np)
print(b_tensor)

b = a.numpy()
print(b)

print(type(b))
print(type(a))

tensor([1., 1., 1., 1., 1.])
[0.5 0.4 2. ]
tensor([0.5000, 0.4000, 2.0000], dtype=torch.float64)
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
<class 'torch.Tensor'>


In [10]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x =  torch.ones(5, device= device)
    print(x)
    #z = x.numpy()
    #print(z)
    
else:
    print("None")

tensor([1., 1., 1., 1., 1.], device='cuda:0')


In [11]:

if torch.cuda.is_available():
    device = torch.device("cuda")
    x =  torch.ones(5, device= device)
    print(x)
    x = x.to("cpu")
    z = x.numpy()
    print(z)

tensor([1., 1., 1., 1., 1.], device='cuda:0')
[1. 1. 1. 1. 1.]


In [12]:
### Means numpy arrays are operated on cpu while torch tensors on gpu as well.


### BackPropagation Theory

In [18]:
x= torch.tensor(1.0)
y= torch.tensor(2.0)

w= torch.tensor(1.0, requires_grad= True)

print(x)
print(y)
print(w)

y_hat = w*x
s = y_hat-y
loss= (s)**2

print(loss.item())

loss.backward()

print(w.grad)
print(w.grad.item())

print(w)

tensor(1.)
tensor(2.)
tensor(1., requires_grad=True)
1.0
tensor(-2.)
-2.0
tensor(1., requires_grad=True)


In [19]:
x = torch.tensor(2.0, requires_grad=True)
y = x ** 2
y.backward()  # Computes the gradient of y with respect to x
print(x.grad)  # Output: 4.0 (since dy/dx = 2 * x)


tensor(4.)


### Building Neural Metwork with torch.nnm

In [24]:
import torch.nn as nn

class SimpleNN(nn.Module):
    def __init__(self):
        super(SimpleNN, self).__init__()
        self.fc1 = nn.Linear(10, 50)
        self.fc2 = nn.Linear(50, 1)
        
    def forward(self, x):
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x
    
model = SimpleNN()

criterion = nn.MSELoss()

optimizer = torch.optim.SGD(model.parameters(), lr= 0.01)

for epoch in range(100):
    inputs = torch.randn(10)
    target = torch.tensor([1.0])
    
    output = model(inputs)
    loss = criterion(output, target)
    
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    
    
from torch.utils.data import DataLoader, TensorDataset

# Creating a simple dataset
x_data = torch.randn(100, 10)  # 100 samples, 10 features
y_data = torch.randn(100, 1)   # 100 targets

dataset = TensorDataset(x_data, y_data)
data_loader = DataLoader(dataset, batch_size=32, shuffle=True)
